### ISSUE TITLE
Unable to proccess multiple failedExecution events with the same nonce

### ISSUE THREAD

**Issue by tcar121293** [sygmaprotocol/sygma-explorer-indexer#171]
Unable to proccess multiple failedExecution events with the same nonce
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Versions
ChainBridge commit (or docker tag):
chainbridge-solidity version:
chainbridge-substrate version:
Go version:

**Comment by LyonSsS** [comment]
Fixed by https://github.com/sygmaprotocol/sygma-explorer-indexer/pull/172 
<img width="1314" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0pZQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--768d1d7068d384f75e9949227484337a471fffe4/image.png" alt="image.png" />
<img width="1252" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM05ZQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--88a53814071767821f1716e5138cf259abb5f9af/image.png" alt="image.png" />
